#ifndef CFG_H
#define CFG_H

#define WINDOW_MAX_DELTA_TIME (0.1F)
#define WINDOW_MAX_PHYSICAL_DEVICES (0x10)
#define WINDOW_MAX_QUEUE_FAMILY_PROPERTIES_COUNT (0xFF)
#define WINDOW_MAX_EXTENSION_PROPERTIES_COUNT (0x400)

#define SWAPCHAIN_MAX_IMAGE_COUNT (0x10)

#define RENDERER_MAX_IMAGE_COUNT (SWAPCHAIN_MAX_IMAGE_COUNT)
#define RENDERER_MAX_FRAMES_IN_FLIGHT (0x10)

#define TRANSFORM_MAX_CHILDREN (0x10)

#define RENDERER_DEBUG_LINE_VERTEX_COUNT (0xFFFFF)
#define RENDERER_DEBUG_LINE_INDEX_COUNT (0xFFFFF)

#define VDB_LOAD_FACTOR (75.0F)
#define VDB_GROWTH_FACTOR (1.618F)
#define VDB_INITIAL_TABLE_COUNT (0x400)

#define VDB_BRICK_MAX_LOD_LEVEL (0x6)
#define VDB_BRICK_SIZE (0x40)
#define VDB_BRICK_VOXEL_WORD_SIZE (0x40)
#define VDB_BRICK_VOXEL_COUNT_LOD6 (0x1)
#define VDB_BRICK_VOXEL_COUNT_LOD5 (0x2)
#define VDB_BRICK_VOXEL_COUNT_LOD4 (0x4)
#define VDB_BRICK_VOXEL_COUNT_LOD3 (0x8)
#define VDB_BRICK_VOXEL_COUNT_LOD2 (0x10)
#define VDB_BRICK_VOXEL_COUNT_LOD1 (0x20)
#define VDB_BRICK_VOXEL_COUNT_LOD0 (0x40)

#endif // CFG_H
