#ifndef CFG_H
#define CFG_H

#define WINDOW_MAX_DELTA_TIME (0.1)
#define WINDOW_MAX_PHYSICAL_DEVICES (0x10)
#define WINDOW_MAX_QUEUE_FAMILY_PROPERTIES_COUNT (0xFF)
#define WINDOW_MAX_EXTENSION_PROPERTIES_COUNT (0x400)

#define SWAPCHAIN_MAX_IMAGE_COUNT (0x10)

#define RENDERER_MAX_IMAGE_COUNT (SWAPCHAIN_MAX_IMAGE_COUNT)
#define RENDERER_MAX_FRAMES_IN_FLIGHT (0x10)

#define TRANSFORM_MAX_CHILDREN (0x10)

#define RENDERER_DEBUG_LINE_VERTEX_COUNT (0xFFFF)
#define RENDERER_DEBUG_LINE_INDEX_COUNT (0xFFFF)

#define VDB_BRICK_LOD (0x4)
#define VDB_COMPUTE_BRICK_WORDS(GRID_SIZE) ((GRID_SIZE * GRID_SIZE * GRID_SIZE) / 0x40)

#endif // CFG_H
