#version 460 core

#extension GL_ARB_shading_language_include : require
#extension GL_EXT_nonuniform_qualifier : require

#include "../vdb/common.glsl"

#define VDB_GET_VOXEL(BRICK_INDEX, VOXEL_POSITION) \
	(uint(imageLoad(vdb_brick[BRICK_INDEX], VOXEL_POSITION).r))

#define VDB_SET_VOXEL(BRICK_INDEX, VOXEL_POSITION, VOXEL) \
	(imageStore(vdb_brick[BRICK_INDEX], VOXEL_POSITION, uvec4(VOXEL, 0, 0, 0)))

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout (binding = 0) uniform vdb_info_t {
	ivec3 cluster_dim;
} vdb_info;
layout (binding = 1, r32ui) uniform uimage3D vdb_brick[];

layout (push_constant) uniform vdb_lod_gen_push_constant_t {
	ivec3 brick_position;
	int brick_index;
	int brick_lod;
} vdb_lod_gen_push_constant;

void main() {
	ivec3 brick_position = vdb_lod_gen_push_constant.brick_position;

	ivec3 curr_voxel_position = ivec3(gl_GlobalInvocationID.xyz);
	ivec3 prev_voxel_position = curr_voxel_position * 2;

	int curr_lod = vdb_lod_gen_push_constant.brick_lod;
	int prev_lod = curr_lod - 1;

	int curr_voxels_per_axis = VDB_VOXELS_PER_AXIS(curr_lod);
	int prev_voxels_per_axis = VDB_VOXELS_PER_AXIS(prev_lod);

	if (curr_voxel_position.x < curr_voxels_per_axis &&
		curr_voxel_position.y < curr_voxels_per_axis &&
		curr_voxel_position.z < curr_voxels_per_axis) {

		int brick_index = vdb_lod_gen_push_constant.brick_index * VDB_MAX_LOD;

		int curr_brick_lod_index = curr_lod + brick_index;
		int prev_brick_lod_index = prev_lod + brick_index;

		uint curr_voxel = VDB_EMPTY_VOXEL;
		uint prev_voxel = VDB_EMPTY_VOXEL;

		bool is_solid = false;

		for (int z = 0; z < 2; z++) {
			for (int y = 0; y < 2; y++) {
				for (int x = 0; x < 2; x++) {

					prev_voxel = VDB_GET_VOXEL(prev_brick_lod_index, prev_voxel_position + ivec3(x, y, z));

					if (VDB_VOXEL_IS_SOLID(prev_voxel)) {
						is_solid = true;
					}
				}
			}
		}

		if (is_solid) {
			curr_voxel = VDB_VOXEL_SET_SOLID(curr_voxel);
		}

		VDB_SET_VOXEL(curr_brick_lod_index, curr_voxel_position, curr_voxel);
	}
}