#version 460 core
#extension GL_ARB_shading_language_include : require

#include "../math/utility.glsl"

#include "../noise/cellular.glsl"
#include "../noise/curl.glsl"
#include "../noise/fbm.glsl"
#include "../noise/gradient.glsl"
#include "../noise/perlin.glsl"
#include "../noise/simplex.glsl"

#include "../vdb/common.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(binding = 2) writeonly buffer vdb_chunk_mask_buffer_t {
    vdb_chunk_mask_t chunk_mask[];
} vdb_chunk_mask_buffer;

layout(push_constant) uniform vdb_world_generator_push_constant_t {
    ivec3 chunk_position;
    int   chunk_index;
} pc;

int get_chunk_index(ivec3 p) {
    ivec3 c = ivec3(VDB_CLUSTER_DIM_X, VDB_CLUSTER_DIM_Y, VDB_CLUSTER_DIM_Z);
    if (any(lessThan(p, ivec3(0))) || any(greaterThanEqual(p, c))) return -1;
    return p.x + p.y * c.x + p.z * c.x * c.y;
}

float vdb_default_density(vec3 sample_position, float ground_level, float cluster_height) {
	float density = 0.0;

	density += noise_cellular_t1((sample_position + vec3(131.0, 11.0, 141.0)) * 0.115, 2.9, 0.3) * 2.44;
	density += noise_curl_t1((sample_position + vec3(887.0, 358.0, 262.0)) * 0.006).x * 14.13;
	density += noise_curl_t1((sample_position + vec3(32.0, 288.0, 204.0)) * 0.045).x * 2.04;

	float norm_y = sample_position.y / cluster_height;
	float height_thresh = ground_level / cluster_height;

	float blend = 1.0 - smoothstep(height_thresh - 0.4, height_thresh + 0.2, norm_y);

	density *= blend;

	//density = soft_terrace(density, 5, 10.0);

	return density;
}

void main() {
    ivec3 local = ivec3(gl_GlobalInvocationID.xyz) - ivec3(1);

    if (any(lessThan(local, ivec3(-1))) ||
        any(greaterThan(local, ivec3(VDB_CHUNK_SIZE))))
    {
        return;
    }

    ivec3 chunk = pc.chunk_position;
    int   cidx  = pc.chunk_index;

    vec3 p = vec3(chunk * VDB_CHUNK_SIZE + local);

    float ground_level   = float(VDB_CLUSTER_DIM_Y * VDB_CHUNK_SIZE) / 2.0;
    float cluster_height = float(VDB_CLUSTER_DIM_Y * VDB_CHUNK_SIZE);

    float density = vdb_default_density(p, ground_level, cluster_height);

    if (density <= VDB_SURFACE_THRESHOLD)
        return;

    float dr = vdb_default_density(p + vec3( 1,0,0), ground_level, cluster_height);
    float dl = vdb_default_density(p + vec3(-1,0,0), ground_level, cluster_height);
    float du = vdb_default_density(p + vec3( 0,1,0), ground_level, cluster_height);
    float dd = vdb_default_density(p + vec3( 0,-1,0), ground_level, cluster_height);
    float df = vdb_default_density(p + vec3( 0,0,1), ground_level, cluster_height);
    float db = vdb_default_density(p + vec3( 0,0,-1), ground_level, cluster_height);

    if (dr <= VDB_SURFACE_THRESHOLD || dl <= VDB_SURFACE_THRESHOLD) {

        int target_chunk_id = cidx;
        uint target_bit = 1u << uint(clamp(local.x, 0, VDB_CHUNK_SIZE - 1));
        uint target_y = uint(clamp(local.y, 0, VDB_CHUNK_SIZE - 1));
        uint target_z = uint(clamp(local.z, 0, VDB_CHUNK_SIZE - 1));
        uint idx = 1u + target_y + target_z * VDB_CHUNK_SIZE;

        if (local.x == VDB_CHUNK_SIZE) {
            ivec3 npos = chunk + ivec3(1,0,0);
            target_chunk_id = get_chunk_index(npos);
            target_bit = 1u << 0u;
        }
        else if (local.x == -1) {
            ivec3 npos = chunk + ivec3(-1,0,0);
            target_chunk_id = get_chunk_index(npos);
            target_bit = 1u << (VDB_CHUNK_SIZE - 1u);
        }

        if (target_chunk_id >= 0) {
            atomicOr(vdb_chunk_mask_buffer.chunk_mask[target_chunk_id].x_mask[idx], target_bit);
            atomicOr(vdb_chunk_mask_buffer.chunk_mask[target_chunk_id].any_x_faces, target_bit);
        }
    }

    if (du <= VDB_SURFACE_THRESHOLD || dd <= VDB_SURFACE_THRESHOLD) {

        int target_chunk_id = cidx;
        uint target_bit = 1u << uint(clamp(local.y, 0, VDB_CHUNK_SIZE - 1));
        uint target_x = uint(clamp(local.x, 0, VDB_CHUNK_SIZE - 1));
        uint target_z = uint(clamp(local.z, 0, VDB_CHUNK_SIZE - 1));
        uint idx = 1u + target_x + target_z * VDB_CHUNK_SIZE;

        if (local.y == VDB_CHUNK_SIZE) {
            ivec3 npos = chunk + ivec3(0,1,0);
            target_chunk_id = get_chunk_index(npos);
            target_bit = 1u << 0u;
        }
        else if (local.y == -1) {
            ivec3 npos = chunk + ivec3(0,-1,0);
            target_chunk_id = get_chunk_index(npos);
            target_bit = 1u << (VDB_CHUNK_SIZE - 1u);
        }

        if (target_chunk_id >= 0) {
            atomicOr(vdb_chunk_mask_buffer.chunk_mask[target_chunk_id].y_mask[idx], target_bit);
            atomicOr(vdb_chunk_mask_buffer.chunk_mask[target_chunk_id].any_y_faces, target_bit);
        }
    }

    if (df <= VDB_SURFACE_THRESHOLD || db <= VDB_SURFACE_THRESHOLD) {

        int target_chunk_id = cidx;
        uint target_bit = 1u << uint(clamp(local.z, 0, VDB_CHUNK_SIZE - 1));
        uint target_x = uint(clamp(local.x, 0, VDB_CHUNK_SIZE - 1));
        uint target_y = uint(clamp(local.y, 0, VDB_CHUNK_SIZE - 1));
        uint idx = 1u + target_x + target_y * VDB_CHUNK_SIZE;

        if (local.z == VDB_CHUNK_SIZE) {
            ivec3 npos = chunk + ivec3(0,0,1);
            target_chunk_id = get_chunk_index(npos);
            target_bit = 1u << 0u;
        }
        else if (local.z == -1) {
            ivec3 npos = chunk + ivec3(0,0,-1);
            target_chunk_id = get_chunk_index(npos);
            target_bit = 1u << (VDB_CHUNK_SIZE - 1u);
        }

        if (target_chunk_id >= 0) {
            atomicOr(vdb_chunk_mask_buffer.chunk_mask[target_chunk_id].z_mask[idx], target_bit);
            atomicOr(vdb_chunk_mask_buffer.chunk_mask[target_chunk_id].any_z_faces, target_bit);
        }
    }
}