#version 460 core

#extension GL_ARB_shading_language_include : require
#extension GL_EXT_nonuniform_qualifier : require

#include "../math/utility.glsl"

#include "../noise/cellular.glsl"
#include "../noise/curl.glsl"
#include "../noise/fbm.glsl"
#include "../noise/gradient.glsl"
#include "../noise/perlin.glsl"
#include "../noise/simplex.glsl"

#include "../vdb/common.glsl"

layout (local_size_x = 8) in;
layout (local_size_y = 8) in;
layout (local_size_z = 8) in;

layout (binding = 0) uniform vdb_cluster_info_t {
	ivec3 cluster_dim;
} vdb_cluster_info;
layout (binding = 1) uniform vdb_terrain_layer_buffer_t {
	vdb_terrain_layer_t terrain_layer[VDB_TERRAIN_LAYER_COUNT];
} vdb_terrain_layer_buffer;
layout (binding = 2) buffer vdb_chunk_mask_buffer_t {
	vdb_chunk_mask_t chunk_mask[];
} vdb_chunk_mask_buffer;

layout (push_constant) uniform vdb_world_generator_push_constant_t {
	ivec3 chunk_position;
	int chunk_index;
} vdb_world_generator_push_constant;

float vdb_default_density(vec3 sample_position, float ground_level, float cluster_height) {
	float density = 0.0;

	density += noise_cellular_t1((sample_position + vec3(131.0, 11.0, 141.0)) * 0.115, 2.9, 0.3) * 2.44;
	density += noise_curl_t1((sample_position + vec3(887.0, 358.0, 262.0)) * 0.006).x * 14.13;
	density += noise_curl_t1((sample_position + vec3(32.0, 288.0, 204.0)) * 0.045).x * 2.04;

	float norm_y = sample_position.y / cluster_height;
	float height_thresh = ground_level / cluster_height;

	float blend = 1.0 - smoothstep(height_thresh - 0.4, height_thresh + 0.2, norm_y);

	density *= blend;

	//density = soft_terrace(density, 5, 10.0);

	return density;
}
float vdb_density_from_layers(vec3 sample_position, float ground_level, float cluster_height) {
	float density = 0.0;

	for (int i = 0; i < VDB_TERRAIN_LAYER_COUNT; i++) {

		vdb_terrain_layer_t terrain_layer = vdb_terrain_layer_buffer.terrain_layer[i];

		switch (terrain_layer.noise_type) {
			case VDB_NOISE_TYPE_CELLULAR: {

				cellular_noise_args_t args = terrain_layer.cellular_noise_args;

				switch (args.type) {
					case VDB_CELLULAR_TYPE_0: {

						switch (args.axis) {
							case VDB_CELLULAR_AXIS_XY: density += noise_cellular_t0((sample_position.xy + args.offset.xy) * terrain_layer.scale, args.u, args.v) * terrain_layer.weight; break;
							case VDB_CELLULAR_AXIS_XZ: density += noise_cellular_t0((sample_position.xz + args.offset.xz) * terrain_layer.scale, args.u, args.v) * terrain_layer.weight; break;
							case VDB_CELLULAR_AXIS_YX: density += noise_cellular_t0((sample_position.yx + args.offset.yx) * terrain_layer.scale, args.u, args.v) * terrain_layer.weight; break;
							case VDB_CELLULAR_AXIS_YZ: density += noise_cellular_t0((sample_position.yz + args.offset.yz) * terrain_layer.scale, args.u, args.v) * terrain_layer.weight; break;
						}

						break;
					}
					case VDB_CELLULAR_TYPE_1: {

						density += noise_cellular_t1((sample_position + args.offset.xyz) * terrain_layer.scale, args.u, args.v) * terrain_layer.weight;

						break;
					}
				}

				break;
			}
			case VDB_NOISE_TYPE_CURL: {

				curl_noise_args_t args = terrain_layer.curl_noise_args;

				// TODO: support vec3.. (using x axis for now)
				switch (args.type) {
					case VDB_CURL_TYPE_0: {

						switch (args.type) {
							case VDB_CURL_AXIS_XY: density += noise_curl_t0((sample_position.xy + args.offset.xy) * terrain_layer.scale).x * terrain_layer.weight; break;
							case VDB_CURL_AXIS_XZ: density += noise_curl_t0((sample_position.xz + args.offset.xz) * terrain_layer.scale).x * terrain_layer.weight; break;
							case VDB_CURL_AXIS_YX: density += noise_curl_t0((sample_position.yx + args.offset.yx) * terrain_layer.scale).x * terrain_layer.weight; break;
							case VDB_CURL_AXIS_YZ: density += noise_curl_t0((sample_position.yz + args.offset.yz) * terrain_layer.scale).x * terrain_layer.weight; break;
						}
					
						break;
					}
					case VDB_CURL_TYPE_1: {
					
						density += noise_curl_t1((sample_position + args.offset.xyz) * terrain_layer.scale).x * terrain_layer.weight;
					
						break;
					}
					case VDB_CURL_TYPE_2: {

						// TODO: support w axis.. (using 0 for now)
						density += noise_curl_t2((vec4(sample_position, 0.0) + args.offset.xyzw) * terrain_layer.scale).x * terrain_layer.weight;
					
						break;
					}
				}

				break;
			}
		}
	}

	float norm_y = sample_position.y / cluster_height;
	float height_thresh = ground_level / cluster_height;

	float blend = 1.0 - smoothstep(height_thresh - 0.2, height_thresh + 0.2, norm_y);

	density *= blend;

	return density;
}

void main() {
	uint chunk_index = vdb_world_generator_push_constant.chunk_index;

	ivec3 chunk_position = vdb_world_generator_push_constant.chunk_position;
	ivec3 voxel_position = ivec3(gl_GlobalInvocationID.xyz);
	
	vec3 sample_position = vec3((chunk_position * VDB_CHUNK_SIZE) + voxel_position);

	float ground_level = float(VDB_CLUSTER_DIM_Y * VDB_CHUNK_SIZE) / 2.0;
	float cluster_height = float(VDB_CLUSTER_DIM_Y * VDB_CHUNK_SIZE);

	//float density = vdb_density_from_layers(sample_position, ground_level, cluster_height);
	//float density = vdb_default_density(sample_position, ground_level, cluster_height);

	float density = vdb_default_density(sample_position, ground_level, cluster_height);

	if (density <= VDB_SURFACE_THRESHOLD) {
		return;
	}

	float density_right = vdb_default_density(sample_position + ivec3(1, 0, 0), ground_level, cluster_height);
	float density_up = vdb_default_density(sample_position + ivec3(0, 1, 0), ground_level, cluster_height);
	float density_front = vdb_default_density(sample_position + ivec3(0, 0, 1), ground_level, cluster_height);

	if (density_right <= VDB_SURFACE_THRESHOLD) {

		uint idx = (voxel_position.y + 1) + (voxel_position.z * VDB_CHUNK_SIZE);
		uint value = 1u << voxel_position.x;

		atomicOr(vdb_chunk_mask_buffer.chunk_mask[chunk_index].x_mask[idx], value);
		atomicOr(vdb_chunk_mask_buffer.chunk_mask[chunk_index].any_x_faces, value);
	}

	if (density_up <= VDB_SURFACE_THRESHOLD) {

		uint idx = (voxel_position.x + 1) + (voxel_position.z * VDB_CHUNK_SIZE);
		uint value = 1u << voxel_position.y;

		atomicOr(vdb_chunk_mask_buffer.chunk_mask[chunk_index].y_mask[idx], value);
		atomicOr(vdb_chunk_mask_buffer.chunk_mask[chunk_index].any_y_faces, value);
	}

	if (density_front <= VDB_SURFACE_THRESHOLD) {

		uint idx = (voxel_position.x + 1) + (voxel_position.y * VDB_CHUNK_SIZE);
		uint value = 1u << voxel_position.z;

		atomicOr(vdb_chunk_mask_buffer.chunk_mask[chunk_index].z_mask[idx], value);
		atomicOr(vdb_chunk_mask_buffer.chunk_mask[chunk_index].any_z_faces, value);
	}
}