#version 460 core

#extension GL_ARB_shading_language_include : require
#extension GL_EXT_nonuniform_qualifier : require

#include "../math/utility.glsl"

#include "../noise/cellular.glsl"
#include "../noise/curl.glsl"
#include "../noise/fbm.glsl"
#include "../noise/gradient.glsl"
#include "../noise/perlin.glsl"
#include "../noise/simplex.glsl"

#define NOISE_TYPE_CELLULAR (0x0)

#define CELLULAR_TYPE_0 (0x0)
#define CELLULAR_TYPE_1 (0x1)

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

struct cellular_noise_args_t {
	vec4 offset;
	int type;
	float u;
	float v;
	int reserved0;
};
struct curl_noise_args_t {
	vec4 offset;
	int type;
	int reserved0;
	int reserved1;
	int reserved2;
};
struct fbm_noise_args_t {
	vec4 offset;
	int type;
	float scale;
	float tile_length;
	float amplitude;
	float lacunarity;
	int octaves;
	int reserved0;
	int reserved1;
};
struct gradient_noise_args_t {
	vec4 offset;
	int type;
	float tile_length;
	int reserved0;
	int reserved1;
};
struct perlin_noise_args_t {
	vec4 offset;
	int type;
	int reserved0;
	int reserved1;
	int reserved2;
};
struct simplex_noise_args_t {
	vec4 offset;
	int type;
	int reserved0;
	int reserved1;
	int reserved2;
};

struct terrain_mod_t {
	cellular_noise_args_t cellular_noise_args;
	curl_noise_args_t curl_noise_args;
	fbm_noise_args_t fbm_noise_args;
	gradient_noise_args_t gradient_noise_args;
	perlin_noise_args_t perlin_noise_args;
	simplex_noise_args_t simplex_noise_args;
	int noise_type;
	float scale;
	int reserved0;
	int reserved1;
};

#include "fwd.glsl"

layout (binding = 0) uniform vdb_info_t {
	ivec3 cluster_dim;
} vdb_info;

layout (binding = 1) uniform vdb_layer_t {
	terrain_mod_t modifier[];
} vdb_layer;

layout (binding = 2, r32ui) uniform uimage3D vdb_brick[];

layout (push_constant) uniform vdb_terrain_gen_push_constant_t {
	ivec3 brick_position;
	int brick_index;
	int brick_lod;
} vdb_terrain_gen_push_constant;

#define EXCLUDE_HDDA_TRACER
#include "vdb.glsl"

float vdb_terrain_from_layers(ivec3 sample_position, float ground_level, float global_height) {
	float density = 0.0;

	terrain_mod_t mod0 = vdb_layer.modifier[0];

	/*
	switch (mod0.noise_type) {
		case NOISE_TYPE_CELLULAR: {

			cellular_noise_args_t args = mod0.cellular_noise_args;

			switch (args.type) {
				case CELLULAR_TYPE_0: {

					density = noise_cellular_t0(position.xz + args.offset.xz, args.u, args.v) * mod0.scale;

					break;
				}
				case CELLULAR_TYPE_1: {

					density = noise_cellular_t1(position.xyz + args.offset.xyz, args.u, args.v) * mod0.scale;

					break;
				}
			}

			break;
		}
	}
	*/

	//density += noise_curl(sample_position * 0.05);
	//density += noise_fbm(sample_position * 0.05, 1.0, 1.0, 4);
	//density += noise_perlin(sample_position * 0.1) * 2.0;
	//density += noise_voronoi(sample_position * 0.1, 0.0, 0.0);
	//density += noise_gradient(sample_position * 0.01);
	//density *= noise_simplex(sample_position * 0.01) * 2.0;
	//density += noise_fbm(sample_position * 0.02, 0.7, 1.0, 4);
	//density += noise_fbm((sample_position + vec3(44324.0223, 213.055, -9895.432)) * 0.04, 0.7, 1.0, 4) * 2.0;

	density = soft_terrace(density, 2, 1.8);

	float height_threshold = ground_level / global_height;
	float blend_factor = smoothstep(height_threshold + 0.2, height_threshold - 0.2, sample_position.y / global_height);

	//density += blend_factor;
	density *= blend_factor;

	return density;
}

void main() {
	ivec3 brick_position = vdb_terrain_gen_push_constant.brick_position;
	ivec3 voxel_position = ivec3(gl_GlobalInvocationID.xyz);
	ivec3 sample_position = (brick_position * VDB_BASE_RES) + voxel_position;

	float ground_level = VDB_CLUSTER_DIM_Y * VDB_BASE_RES / 2.0;
	float global_height = VDB_CLUSTER_DIM_Y * VDB_BASE_RES;
	float terrain_density = vdb_terrain_from_layers(sample_position, ground_level, global_height);

	int brick_index = VDB_BRICK_INDEX(brick_position.x, brick_position.y, brick_position.z);

	uint voxel = VDB_GET_VOXEL(0, brick_index, voxel_position);

	if (terrain_density > 0.0) {
		voxel &= ~VDB_VOXEL_IS_SOLID_BIT;
	} else {
		voxel |= VDB_VOXEL_IS_SOLID_BIT;
	}

	VDB_SET_VOXEL(0, brick_index, voxel_position, voxel);
}