#version 460 core

#extension GL_ARB_shading_language_include : require
#extension GL_EXT_nonuniform_qualifier : require

#include "../math/utility.glsl"

#include "../noise/cellular.glsl"
#include "../noise/curl.glsl"
#include "../noise/fbm.glsl"
#include "../noise/gradient.glsl"
#include "../noise/perlin.glsl"
#include "../noise/simplex.glsl"

#include "../vdb/common.glsl"

#define VDB_GET_VOXEL(BRICK_INDEX, VOXEL_POSITION) \
	(uint(imageLoad(vdb_brick[BRICK_INDEX], VOXEL_POSITION).r))

#define VDB_SET_VOXEL(BRICK_INDEX, VOXEL_POSITION, VOXEL) \
	(imageStore(vdb_brick[BRICK_INDEX], VOXEL_POSITION, uvec4(VOXEL, 0, 0, 0)))

#define NOISE_TYPE_CELLULAR (0x0)

#define CELLULAR_TYPE_0 (0x0)
#define CELLULAR_TYPE_1 (0x1)

struct cellular_noise_args_t {
	vec4 offset;
	int type;
	float u;
	float v;
	int reserved0;
};
struct curl_noise_args_t {
	vec4 offset;
	int type;
	int reserved0;
	int reserved1;
	int reserved2;
};
struct fbm_noise_args_t {
	vec4 offset;
	int type;
	float scale;
	float tile_length;
	float amplitude;
	float lacunarity;
	int octaves;
	int reserved0;
	int reserved1;
};
struct gradient_noise_args_t {
	vec4 offset;
	int type;
	float tile_length;
	int reserved0;
	int reserved1;
};
struct perlin_noise_args_t {
	vec4 offset;
	int type;
	int reserved0;
	int reserved1;
	int reserved2;
};
struct simplex_noise_args_t {
	vec4 offset;
	int type;
	int reserved0;
	int reserved1;
	int reserved2;
};

struct vdb_world_mod_t {
	cellular_noise_args_t cellular_noise_args;
	curl_noise_args_t curl_noise_args;
	fbm_noise_args_t fbm_noise_args;
	gradient_noise_args_t gradient_noise_args;
	perlin_noise_args_t perlin_noise_args;
	simplex_noise_args_t simplex_noise_args;
	int noise_type;
	float scale;
	int reserved0;
	int reserved1;
};

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout (binding = 0) uniform vdb_info_t {
	ivec3 cluster_dim;
} vdb_info;
layout (binding = 1) uniform vdb_layer_t {
	vdb_world_mod_t modifier[];
} vdb_layer;
layout (binding = 2, r32ui) uniform uimage3D vdb_brick[];

layout (push_constant) uniform vdb_world_gen_push_constant_t {
	ivec3 brick_position;
	int brick_index;
} vdb_world_gen_push_constant;

float vdb_density_from_layers(vec3 sample_position, float ground_level, float cluster_height) {
	vdb_world_mod_t mod0 = vdb_layer.modifier[0];

	/*
	switch (mod0.noise_type) {
		case NOISE_TYPE_CELLULAR: {

			cellular_noise_args_t args = mod0.cellular_noise_args;

			switch (args.type) {
				case CELLULAR_TYPE_0: {

					density = noise_cellular_t0(sample_position.xz + args.offset.xz, args.u, args.v) * mod0.scale;

					break;
				}
				case CELLULAR_TYPE_1: {

					density = noise_cellular_t1(sample_position.xyz + args.offset.xyz, args.u, args.v) * mod0.scale;

					break;
				}
			}

			break;
		}
	}
	*/

	float norm_y = sample_position.y / cluster_height;

	float base = noise_gradient(sample_position * 0.008);
	float detail_low  = noise_gradient(sample_position * 0.035);
	float detail_mid  = noise_gradient(sample_position * 0.09  * (1.0 + norm_y * 4.0));
	float detail_high = noise_gradient(sample_position * 0.22  * (1.0 + norm_y * 8.0));

	float density = base * 1.4; // + detail_low * 0.7 + detail_mid * 0.4 + detail_high * 0.25;

	// density += (norm_y - 0.45) * -1.2;
	// density += sin(p.y * 0.08 + base * 4.0) * 0.35;

	float blend = 1.0 - smoothstep(0.1, 0.3, norm_y);

	density *= blend;

	// density -= 0.3; // moves iso-surface down

	return density;
}

void main() {
	ivec3 brick_position = vdb_world_gen_push_constant.brick_position;
	ivec3 voxel_position = ivec3(gl_GlobalInvocationID.xyz);
	
	vec3 sample_position = vec3((brick_position * VDB_BASE_RES) + voxel_position);

	float ground_level = float(VDB_CLUSTER_DIM_Y * VDB_BASE_RES) / 2.0;
	float cluster_height = float(VDB_CLUSTER_DIM_Y * VDB_BASE_RES);

	float density = vdb_density_from_layers(sample_position, ground_level, cluster_height);

	uint brick_index = vdb_world_gen_push_constant.brick_index * VDB_LOD_COUNT_PLUS_ONE;

	uint voxel = VDB_EMPTY_VOXEL;

	if (density > 0.0) {
		voxel = VDB_VOXEL_SET_SOLID(voxel);
	}

	VDB_SET_VOXEL(brick_index, voxel_position, voxel);
}